priority fix
moonlibs/xqueue pull request #9
Opened 2019-10-14 17:04 UTC by max101101

2019-10-15 13:11 UTC, orchaton commented
After catching optional field `priority` we must search for `status_priority_id` index and throw separate exception if this index is not found.

Otherwise, we must fall back to searching `status_id` inde instead

2019-10-15 13:12 UTC, ochaton reviewed
Needs corrections

2019-10-15 13:12 UTC, orchaton commented on xqueue.lua
> +					if index.parts[1].fieldno == fields.status
Check for `#index.parts >= 3 is missing`

2019-10-15 13:12 UTC, orchaton commented on xqueue.lua
> +				elseif index.parts[1].fieldno == fields.status
It is better to use `else` here and nested `if` check inside. Also we have to check that `#index.parts >= 2`.

2019-10-17 11:03 UTC, Mons requested changes

2019-10-17 11:03 UTC, Mons commented on xqueue.lua
> +				end
вместо `if abc then return true` можно писать `return abc`

2019-10-17 11:03 UTC, Mons commented on xqueue.lua
> +					return true
то-же самое

2019-10-17 11:03 UTC, Mons commented on xqueue.lua
> +				self.index = index
если индекс передан, мы не должны его перетирать, а только проверять

2019-10-17 12:20 UTC, orchaton commented on xqueue.lua
> +				self.index = index
@Mons self.index высчитывается этим кодом. В документации не описаны способы передачи индекса, а также по коду видно, что передать индекс в xqueue нельзя

2019-10-17 12:50 UTC, Mons approved these changes

2019-10-18 11:56 UTC, merged